### ISSUE TITLE
Post Writing CMS Checklist 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#14]
We are currently building the CMS for writing and sending an internal email for Volkswagen. This includes drafting a post, putting together an email, scheduling the email, and offering smart suggestions for each day's post queue. This milestone is due **April 6th, 2020**

In this issue we are making the pages in the process of creating an article. These are the pages:

- [x] Choose Category #15
User chooses the category of the article they are writing, which will affect the information collected, the prioritization, and the positioning of the article on the email. 
![Choose Category](https://user-images.githubusercontent.com/5694308/78211300-c7ac4280-74d6-11ea-8c2f-8d098e9a5afb.png)

- [ ] New Event Form #17 
This is the form specifically for an article in the event category, which collects price, date/time, and images as well as a title and description of the event
![Event Form](https://user-images.githubusercontent.com/5694308/78211393-0510d000-74d7-11ea-9958-5002e7fee51d.png)

- [ ] Answers At A Glance Form #18 
This is the form specifically for answers at a glance category , which takes a question and an answer, and doesn't have an image.
![Answers At A Glance](https://user-images.githubusercontent.com/5694308/78211396-06da9380-74d7-11ea-9598-8e70230305e9.png)

- [ ] New Article (Other Categories) #16 
This is the form for all categories except for Events and Answers at a Glance, which includes headline and the description. 
![Category Article](https://user-images.githubusercontent.com/5694308/78211395-0641fd00-74d7-11ea-94ca-e1645ce2c28f.png)

- [ ] Schedule/Submit Post #20 
The schedule post page allows you to preview the article in its section as well as selecte a date 
![Submit Post](https://user-images.githubusercontent.com/5694308/78212314-85d0cb80-74d9-11ea-89b5-b6c59e67d6b1.png)
![Schedule Post](https://user-images.githubusercontent.com/5694308/78212316-8701f880-74d9-11ea-84b0-32655ef5f863.png)

- [ ] Image Preview #19
This page can only be accessed during the writing of the article in forms where there is a photo upload step. It displays the image uploaded and allows user to delete the image at this step. 
![Portfolio Gallery Lightbox](https://user-images.githubusercontent.com/5694308/78222886-32b64300-74f0-11ea-8c41-5b76d28d2453.png)

### Design File
The specs for each individual style can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)
