### ISSUE TITLE
Memo CMS Checklist

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#64]
This is part of the internal memo flow for Volkswagen's internal newsletter/memo app

# Design 
For design specs, go to the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

Your mission, should you choose to accept: 

This is the checklist for the internal memo creating flow 

- [x] Dashboard FAB Button
![image](https://user-images.githubusercontent.com/5694308/79037426-ff179f00-7bfa-11ea-94e1-3d915e942e38.png)

- [x] Internal Memo Drafting #62 
![New Internal Memo](https://user-images.githubusercontent.com/5694308/79037429-08a10700-7bfb-11ea-8e93-e12c1bb95888.JPG)

- [x] Internal Memo Preview #63 
![Preview Memo](https://user-images.githubusercontent.com/5694308/79037430-0c348e00-7bfb-11ea-8c07-693176280c94.JPG)

- [x] Success Screen #28 
![Success](https://user-images.githubusercontent.com/5694308/79037433-0f2f7e80-7bfb-11ea-8340-a8fe967afb01.JPG)

- [x] Internal Memo Drafting Desktop #65 
![image](https://user-images.githubusercontent.com/5694308/79108946-96b6f200-7da1-11ea-9e58-5983aed2c627.png)

- [x] Internal Memo Preview Desktop #67
![image](https://user-images.githubusercontent.com/5694308/79108911-8868d600-7da1-11ea-8b2f-6d5e71384776.png)

- [x] Success Screen Desktop #68
![image](https://user-images.githubusercontent.com/5694308/79108972-9fa7c380-7da1-11ea-9991-5129dfe626e6.png)
