### ISSUE TITLE
Memo Tracking - Open Rate Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#77]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

this is the "open rate" page for each individual memo that shows memo tracking 
![image](https://user-images.githubusercontent.com/5694308/79435010-5baefb80-7ff9-11ea-9030-8f5f0ab5e47c.png)

Your mission, should you accept, includes these tasks: 

- [x] 1. [Top Navigation ](#top-navigation) #25 
- [ ] 2. [Search Bar](#search-bar) 
- [x] 3. [Memo Info](#memo-info)
- [x] 4. [Tabs](#tabs)
- [x] 5. [Opened List](#opened-list)
- [x] 6. [Unread List](#unread-list)

<h1 id="top-navigation">1. Top Navigation</h1> 

## Content
This is similar to #25 EXCEPT 
1. no stepper navigation section
2. No Text Action 

Title: Open Rate
Back Icon: (Leads to #76 Memo Activity Feed )

<h1 id="search-bar">2. Search Bar</h1> 

![image](https://user-images.githubusercontent.com/5694308/79432651-50a69c00-7ff6-11ea-8e7b-2741ca808aec.png)

## Content 
Text: Search

## Asset 
Search Icon 
![search](https://user-images.githubusercontent.com/5694308/79432804-864b8500-7ff6-11ea-8bf9-79ea9da2f3d4.png)

## Text Style 
Text: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Color
Search Bar Background: Surface (#FFFFFF) 

<h1 id="memo-info">3. Memo Tracking Info</h1> 

![image](https://user-images.githubusercontent.com/5694308/79435272-a16bc400-7ff9-11ea-9402-84fe33ddf17c.png)

## Content 
**Title:** {{ Memo Subject Line }} 
**Date:** {{ Memo Date }} 
**Audience:** To: {{ Audience }} 
**Stats Title:** Open rate: {{open rate}}
**Stats Bar:** {{ Display open rate in blue progress bar }} 

## Text Style
Title:
```
/* Body 1 Emphasis */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Date, Audience, Open rate: 
```
/* Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

## Color
Title: On Background High Emphasis (#000000, 84%)
Date: On Background Disabled (#000000, 38%) 
Audience: On Background High Emphasis (#000000, 84%) 
Open Rate: On Background High Emphasis (#000000, 84%) 
Progress Bar Background: On Background, Divider (#000000, 12%) 
Progress Bar: 
```
/* Light Blue Gradient */

background: linear-gradient(90deg, #0374F9 0%, #03B3F9 100%);
```

<h1 id="tabs">4. Opened/Unread Tabs</h1> 

![image](https://user-images.githubusercontent.com/5694308/79435470-e5f75f80-7ff9-11ea-9fea-6b2ed9ad30dd.png)

## Content 
Tab Title 1: Opened (shows list of people who've opened memo)
Tab Title 2: Unread (shows list of people who didn't read memo)

## Text Style 
Tab Titles: 
```
/* Color Label */

font-family: Work Sans;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* identical to box height, or 171% */

letter-spacing: 0.02em;
text-transform: uppercase;
```

## Color
Tab Title: Primary (#011D51)
Tab Background: Surface (#FFFFFF) 
Active Tab Indicator: Secondary (#03B3F9)

## Shadow
```
/* 4 dp */

background: #C4C4C4;
box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

<h1 id="opened-list">5. Opened List</h1>

![image](https://user-images.githubusercontent.com/5694308/79436070-9ebd9e80-7ffa-11ea-8a78-9fb7f3c75184.png)
This is a list of people who have opened the memo 

## Content
**Title:** To: {{ email }} 
**Received:** Received: {{ Date/Time Received }} 
**Opened:** Opened: {{ Date/Time Received }}

## Text Style 
Title: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Received, Opened: 
```
/* Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

## Color 
Title: On Background High Emphasis (#000000, 84%) 
Recieved, Opened: On Background, Disabled (#000000, 38%) 

<h1 id="unread-list">6. Unread List</h1> 
 
![image](https://user-images.githubusercontent.com/5694308/79436103-a8470680-7ffa-11ea-9db1-cd967957f378.png)
this is a list of people who have not read the memo 

## Content
**Title:** To: {{ email }} 
**Received:** Received: {{ Date/Time Received }} 

## Text Style 
Title: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Received: 
```
/* Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

## Color 
Title: On Background High Emphasis (#000000, 84%) 
Recieved: On Background, Disabled (#000000, 38%)

**Comment by paulchrisluke** [comment]
# Tabs 
![image](https://user-images.githubusercontent.com/5694308/80334658-1487fc80-887c-11ea-9ad0-02331dc35c71.png)
Tab text should be centered within the tab 

![image](https://user-images.githubusercontent.com/5694308/80334732-46995e80-887c-11ea-8e2f-d7cb3c591fe8.png)
I know we're not working on desktop visuals yet, but extend the tab background to full screen(responsively) just so it doesn't look as awkward visually
ONLY the tab background, keep the rest of the content within its space

# Search Bar 
![image](https://user-images.githubusercontent.com/5694308/80334938-f2db4500-887c-11ea-8715-384e7c49730e.png)
![image](https://user-images.githubusercontent.com/5694308/80334975-143c3100-887d-11ea-82ea-0427fc4ff0d3.png)

No floating label for the search bar. Have the "search" label there, and then when they click into it and start typing, replace "search" label with inputted text (do the same thing for "Activity Feeds" page)

# "Opened" List 
![image](https://user-images.githubusercontent.com/5694308/80335016-37ff7700-887d-11ea-92ad-fbe1e0b54721.png)
The current list doesn't actually show "time received", and doesn't show "time opened" at all 

# "Unread" List 
![image](https://user-images.githubusercontent.com/5694308/80335080-6d0bc980-887d-11ea-8213-07a6e9bd038e.png)
The current list should show "time received"

**Comment by mort3za** [comment]
@ctyar @bamboochow Received/Opened times are null from API. 

will fix other bugs
